#! /bin/bash
EXEC=../dist/thorn-local.sh
TMP=/var/tmp

src="$1"
ntests="$2"
function perf () {
    printf "mu:,%s," $src
    echo -n `bash $EXEC --pipe --eval="(core::storage-delta (:lambda () $1) :nil)"`
    for i in $(seq 1 $ntests)
    do
        printf ",%s" `bash $EXEC --pipe --eval="(core::time-delta (:lambda () $1) :nil)"`
    done
    echo
}

source $src > $TMP/thorn-perf.$$.log 2>&1
cat $TMP/thorn-perf.$$.log
rm -f $TMP/thorn-perf.$$.log

exit 0
