#! /bin/bash
EXEC=../dist/runtime
TMP=/var/tmp

args=("$@")
opts=("${args[@]:1}")

function assert_eq () {
    result=`$EXEC ${opts[@]} -p -e "$1"`

    if [ $? -eq 0 ]
    then
       if [ "$result" != "$2" ]
       then
           echo -e "$1","$2","$result",failed
       else
           echo -e "$1","$2","$result",passed
       fi
    else
        echo -e "$1",aborted
    fi
}

source "$1" >> $TMP/thorn-test.$$.log 2>&1

total=`egrep -c -v "^#" $1`
failed=`grep -c failed $TMP/thorn-test.$$.log`
aborted=`grep -c aborted $TMP/thorn-test.$$.log`
file=`basename "$1"`

echo "mu:",$file,$total,$failed,$aborted
cat $TMP/thorn-test.$$.log

rm -f $TMP/thorn-test.$$.log

exit 0
